In [1]:
!pip install numpy

# 1. Create 3x3 array with random values.

In [16]:
import numpy as np

# 3x3 array with random values

arr = np.random.rand(3, 3) 

print(arr)

[[0.24244869 0.91648183 0.19488056]
 [0.58924494 0.90512106 0.97123596]
 [0.71212178 0.92546515 0.18192918]]


# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [19]:
import numpy as np

# Create a 5x5 matrix filled with zeros

arr_matrix = np.zeros((5, 5), dtype=int)

# Fill values 1, 2, 3, and 4 just below the diagonal

for i in range(1, 5):
    
    arr_matrix[i, i - 1] = i

print(arr_matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3. Create a 8x8 matrix and fill it with a checkerboard pattern 

In [23]:
import numpy as np


arr_matrix1 = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern (alternating 1s and 0s)

arr_matrix1[1::2, ::2] = 1  # Even-Rows , Odd-Columns 

arr_matrix1[::2, 1::2] = 1  # Odd-Rows , Even-Columns 

print(arr_matrix1)


print('\n#--------------------- Alternative Way ---------------------#')


print('\n# Using numpy <tile>')

arr_matrix2 = np.tile([[0, 1], [1, 0]], (4, 4))

print("\n",arr_matrix2)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

#--------------------- Alternative Way ---------------------#

# Using numpy <tile>

 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix 

In [27]:
import numpy as np

# Create a 5x5 random matrix

random_matrix = np.random.rand(5, 5)

# Find the minimum and maximum values in the matrix

min_value = np.min(random_matrix)

max_value = np.max(random_matrix)


#-------------------- Normalizing Matrix [0, 1] --------------------#


normalized_matrix = (random_matrix - min_value) / (max_value - min_value)

print("\nOriginal random matrix:")

print("\n",random_matrix)

print("\nNormalized matrix:")

print("\n",normalized_matrix)



Original random matrix:

 [[0.07672784 0.67739959 0.441549   0.4302562  0.67568841]
 [0.07007528 0.03141182 0.39528277 0.13448675 0.7852929 ]
 [0.290371   0.70267155 0.16766872 0.0948301  0.41027134]
 [0.50593524 0.45369309 0.06680355 0.73040775 0.39604116]
 [0.21048283 0.37546365 0.53569344 0.17981336 0.59192784]]

Normalized matrix:

 [[0.06011031 0.85688286 0.54403432 0.52905477 0.85461303]
 [0.05128589 0.         0.4826636  0.13672572 1.        ]
 [0.34350137 0.89040533 0.18074058 0.0841224  0.50254547]
 [0.62944069 0.56014308 0.04694604 0.92719655 0.48366957]
 [0.23753217 0.45637414 0.66891402 0.19685007 0.74350722]]


# 5. How to find common values between two arrays?

In [31]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])

array2 = np.array([3, 4, 5, 6, 7])

#-------------------- Common Values --------------------#

common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)


Common values: [3 4 5]


# 6. How to get the dates of yesterday, today and tomorrow? 

In [33]:
from datetime import datetime

import numpy as np


print("\n #---------- Today's Date ----------#")

todays_date = datetime.now()

print(todays_date)


print("\n #---------- Yesterday Date ----------#")

yesterday_date = np.datetime64('today', 'D')- np.timedelta64(1, 'D')

print(yesterday_date)


print("\n #---------- Tomorrow's Date ----------#")

tomorrow_date = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(tomorrow_date)


 #---------- Today's Date ----------#
2023-09-22 14:44:19.570672

 #---------- Yesterday Date ----------#
2023-09-21

 #---------- Tomorrow's Date ----------#
2023-09-23


# 7. Consider two random array A and B, check if they are equal 

In [36]:
import numpy as np

array_1 = np.random.rand(5)  

array_2 = np.random.rand(5)  


#-------------------- Numpy (array_equal) method --------------------#


arr_comparison = np.array_equal(array_1, array_2)

if arr_comparison:
    
    print("\n Array 1 & Array 2 are equal.")
    
else:
    
    print("\n Array 1 & Array 2 are not equal.")



 Array 1 & Array 2 are not equal.


# 8. Create random vector of size 10 and replace the maximum value by 0 

In [38]:
import numpy as np

#-------------------- Random vector (size 10) --------------------#

rand_vector = np.random.rand(10)

#-------------------- Replace Max with 0 --------------------#

rand_vector[np.argmax(rand_vector)] = 0

print("\n#-------------------- Modified Vector --------------------#")

print("\n",rand_vector)


#-------------------- Modified Vector --------------------#

 [0.         0.36482551 0.11994183 0.26375234 0.2205466  0.59894311
 0.53820736 0.37725722 0.0058053  0.41685151]


# 9. How to print all the values of an array? 

In [44]:
import numpy as np

my_array = np.array([[10, 20, 30, 40, 50],
                     [60, 70, 80, 90, 100]])

for row in my_array:
    
    for value in row:
        
        print(value,end=' ')


10 20 30 40 50 60 70 80 90 100 

# 10. Subtract the mean of each row of a matrix 

In [45]:
import numpy as np

def_matrix = np.random.rand(5, 10)

print("Original matrix:\n")

print(def_matrix)

#-------------------- Subtract mean of each row of the matrix --------------------

print("\nSubtracted Matrix is:\n")

sub_matrix = def_matrix - def_matrix.mean(axis=1, keepdims=True)

print(sub_matrix)


Original matrix:

[[0.41765022 0.41617391 0.11869601 0.58866194 0.2526933  0.57717783
  0.43231294 0.01791639 0.94957366 0.21924399]
 [0.5024436  0.76037091 0.98923124 0.87484874 0.12173024 0.75910182
  0.8721673  0.40934113 0.34046482 0.94725352]
 [0.76675941 0.12895654 0.27938681 0.03358857 0.56999141 0.42111891
  0.77512015 0.13311689 0.67869523 0.63735004]
 [0.05177716 0.09725997 0.34589135 0.84334227 0.15790813 0.82451015
  0.08643088 0.15325796 0.24474439 0.77161107]
 [0.39496679 0.93856569 0.93539837 0.27662083 0.3913606  0.57846973
  0.62719637 0.79091575 0.83132886 0.82739922]]

Subtracted Matrix is:

[[ 0.0186402   0.01716389 -0.28031401  0.18965192 -0.14631672  0.17816781
   0.03330292 -0.38109363  0.55056364 -0.17976602]
 [-0.15525173  0.10267558  0.33153591  0.21715341 -0.5359651   0.10140649
   0.21447196 -0.2483542  -0.31723051  0.28955819]
 [ 0.32435102 -0.31345186 -0.16302158 -0.40881983  0.12758301 -0.02128948
   0.33271175 -0.30929151  0.23628683  0.19494164]
 [-0.30

# 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [49]:
import numpy as np

vector = np.array([10, 20, 30, 40])

vector_indices = np.array([0, 1, 2, 3])

print("\n Default Vector:")

print(vector)

#-------------------- Adding 1 to Elements --------------------#

result_vector = vector[vector_indices] + 1

print("\n Updated Vector <+1 Added>:")

print(result_vector)


 Default Vector:
[10 20 30 40]

 Updated Vector <+1 Added>:
[11 21 31 41]


# 12. How to get the diagonal of a dot product? 

In [52]:
import numpy as np

array_1 = np.random.rand(3,3) 

array_2 = np.random.rand(3,3)

print("\n Diagonal Dot product: ")

print(np.diag(np.dot(array_1, array_2)))

print(array_1)


 Diagonal Dot product: 
[0.77312689 0.07806388 0.17844601]
[[0.0082905  0.93609463 0.77304894]
 [0.02374602 0.04136052 0.31383731]
 [0.05260036 0.63984297 0.06405529]]


# 13. How to find the most frequent value in an array? 

In [55]:
import numpy as np

user_array = np.array([10, 10, 20, 30, 30, 30, 30, 40, 40])

#-------------------- Numpy (bincount , argmax) --------------------#

most_freq_values = np.bincount(user_array).argmax()

# Print the most frequent value(s)

print("Most frequent values from array is :", most_freq_values)


Most frequent values from array is : 30


# 14. How to get the n largest values of an array

In [60]:
import numpy as np

array_random= np.arange(500)

np.random.shuffle(array_random)

n_large = 2

print("\n N largest values:", end=' ')

print (array_random[np.argsort(array_random)[-n_large:]])



 N largest values: [498 499]


# 15. How to create a record array from a regular array? 

In [68]:
import numpy as np

regular_array = np.array([(1, 'Emp1', 10),
                          (2, 'Emp2', 20),
                          (3, 'Emp3', 30)],
                         dtype=[('id', int), ('name', 'U10'), ('age', int)])

# Create a record array from the regular array

record_array = np.rec.fromarrays(regular_array.T, 
                                 names=regular_array.dtype.names)

#--------------- Recorded array ---------------#

print(record_array, "\n")


((1, 'Emp1', 10), (2, 'Emp2', 20), (3, 'Emp3', 30)) 



# 16. How to swap two rows of an array?

In [81]:
import numpy as np

#-------------------- Initial Array --------------------# 

arr = np.random.randint(0, 5, size=(4, 4))

print("\nInitial Array:\n")

print(arr)

#-------------------- Array Indices --------------------# 

row1_index = 1

row2_index = 3

#-------------------- Swapping Rows --------------------# 

arr[[row1_index, row2_index], :] = arr[[row2_index, row1_index], :]


#-------------------- Updated Array (Swapped Rows) -------------------- #

print("\nUpdated Array:\n")

print(arr)


#-------------------- Alternate Way ------------------------------------#

a = np.array([[4,3, 1],[5 ,7, 0],[9, 9, 3],[8, 2, 4]]) 

print(a)


a[[0, 2]] = a[[2, 0]]

print(a)


Initial Array:

[[3 0 4 0]
 [3 1 1 0]
 [1 2 1 3]
 [0 0 3 4]]

Updated Array:

[[3 0 4 0]
 [0 0 3 4]
 [1 2 1 3]
 [3 1 1 0]]


# 17. Write python code to reshape to the next dimension of numpy array? 

In [87]:
import numpy as np

user_arr = np.random.randint(0, 5, size=(3, 2))

print("\n Before Reshaping: \n")

print(user_arr)

#-------------------- Reshape to 2 x 3 --------------------#

user_arr = user_arr.reshape((2, 3))

print("\n After Reshaping:\n")

#--------------- Resulting array ---------------#

print(user_arr)



 Before Reshaping: 

[[4 4]
 [3 1]
 [1 4]]

 After Reshaping:

[[4 4 3]
 [1 1 4]]


# Numpy - Mini Case Study 2 (Practice Assignments)

In [3]:
import numpy as np 

np_olympic_country = np.array(['GBR', 'Chine', 'RUS', 'US', 'KOR', 'JPN', 'GER'])

np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

np_olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])

np_olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

# 1. Find the country index with maximum Gold

In [4]:
max_gold_index = np.argmax(np_olympic_country_gold)

print("\nCountry with Maximum Gold Medals:", np_olympic_country[max_gold_index])

print("\nIndex in the Array is :", max_gold_index)


Country with Maximum Gold Medals: US

Index in the Array is : 3


# 2. Print Country with Maximum Gold

In [5]:
country_with_max_gold = np_olympic_country[max_gold_index]

print("\nCountry with Maximum Gold Medals is :", country_with_max_gold)


Country with Maximum Gold Medals is : US


# 3. Find countries with more than 20 gold medals

In [6]:
countries_with_more_than_20_gold = np_olympic_country[np_olympic_country_gold > 20]

print("\nCountries with More Than 20 Gold Medals are:", countries_with_more_than_20_gold)


Countries with More Than 20 Gold Medals are: ['GBR' 'Chine' 'RUS' 'US']


# 4. Evaluate the dataset and print the medal 

In [8]:
for i in range(len(np_olympic_country)):
    
    country = np_olympic_country[i]
    
    gold = np_olympic_country_gold[i]
    
    silver = np_olympic_country_silver[i]
    
    bronze = np_olympic_country_bronze[i]
    
    print(f"\nCountry - {country}: \n Gold: {gold}, \n Silver: {silver}, \n Bronze: {bronze}")


Country - GBR: 
 Gold: 29, 
 Silver: 17, 
 Bronze: 19

Country - Chine: 
 Gold: 38, 
 Silver: 28, 
 Bronze: 22

Country - RUS: 
 Gold: 24, 
 Silver: 25, 
 Bronze: 32

Country - US: 
 Gold: 46, 
 Silver: 28, 
 Bronze: 29

Country - KOR: 
 Gold: 13, 
 Silver: 8, 
 Bronze: 7

Country - JPN: 
 Gold: 7, 
 Silver: 14, 
 Bronze: 17

Country - GER: 
 Gold: 11, 
 Silver: 11, 
 Bronze: 14
